# Generated by Django 5.1.1 on 2024-09-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Done', models.BooleanField(default=False)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
